### ISSUE TITLE
Documentacion Externa

### ISSUE THREAD

**Issue by Carlos12001** [Carlos12001/Build_a_Tree#4]

**Comment by Carlos12001** [comment]
Ya se tiene el la descripcion breve

**Comment by Carlos12001** [comment]
Ya se realizo el la descripcion breve

**Comment by Carlos12001** [comment]
![BTS](https://user-images.githubusercontent.com/62664256/101059494-f42bc900-3553-11eb-8ad3-b1974262e1e2.png)

**Comment by Carlos12001** [comment]
![AVL](https://user-images.githubusercontent.com/62664256/101059555-04dc3f00-3554-11eb-8028-dcea63ba65c5.png)

**Comment by Carlos12001** [comment]
![B](https://user-images.githubusercontent.com/62664256/101059583-0efe3d80-3554-11eb-80e2-10280dd94f3f.png)

**Comment by Carlos12001** [comment]
![Splay](https://user-images.githubusercontent.com/62664256/101059619-1887a580-3554-11eb-8bad-16522db228d8.png)

**Comment by Carlos12001** [comment]
![AbstractTree](https://user-images.githubusercontent.com/62664256/101060089-9fd51900-3554-11eb-914a-a344f2e076f4.png)

**Comment by Apollo13-0** [comment]
Link al pdf con diagrama
[Diagrama de clases BAT.pdf](https://github.com/Carlos12001/Build_a_Tree/files/5637938/Diagrama.de.clases.BAT.pdf)

**Comment by Carlos12001** [comment]
![Paquetes](https://user-images.githubusercontent.com/62664256/101077384-61e2ef80-356a-11eb-9eee-02c6c4db37cb.png)

**Comment by Carlos12001** [comment]
![Paquetes](https://user-images.githubusercontent.com/62664256/101081515-c8b6d780-356f-11eb-87d9-4d2a37580cdc.png)

**Comment by Apollo13-0** [comment]
![Diagrama en blanco - Diagrame de arquitectura](https://user-images.githubusercontent.com/53590021/101085143-a3789800-3574-11eb-8f69-080ee205de0e.png)

**Comment by Apollo13-0** [comment]
![Diagrama en blanco - Diagrama de clases (1)](https://user-images.githubusercontent.com/53590021/101106578-fca4f380-3595-11eb-8493-d6c7634ec989.png)

**Comment by Apollo13-0** [comment]
![Diagrama en blanco - Diagrama de clases (1)](https://user-images.githubusercontent.com/53590021/101106667-2eb65580-3596-11eb-9be6-79bd663090ca.png)

**Comment by Apollo13-0** [comment]
[Diagrama de Clases Tree.pdf](https://github.com/Carlos12001/Build_a_Tree/files/5639878/Diagrama.de.Clases.Tree.pdf)
